import { useState } from 'react'
{{#if USE_ANTD}}
import { Button } from 'antd'
{{/if}}

interface Props {
  /** Storybook will pick up this comment as the description of the prop next line. */
  name: string
}

/** Description of component {{ COMPONENT_NAME }}. Like props, it will appear in document generated by Storybook */
export function {{ COMPONENT_NAME }}({ name }: Props) {
  let [count, setCount] = useState(0)
  return (
    <div>
      Hello {name}!
      Count: {count}
      {{#if USE_ANTD}}
      <Button onClick={() => setCount(count + 1)} type="primary">Increment</Button>
      {{else}}
      <button onClick={() => setCount(count + 1)}>Increment</button>
      {{/if}}
    </div>
  )
}

export default {{ COMPONENT_NAME }}